name: kharcha
description: >
  Kharcha â€“ Your Smart Expense Tracker.
  A modern Nepali financial management app that tracks daily expenses,
  income, multi-wallet (cash, eSewa, bank), budgets, BS calendar,
  and shows analytics with pie charts and bar charts.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --------------------------
  # DATABASE & STORAGE
  # --------------------------
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # --------------------------
  # UI / UTILITIES
  # --------------------------
  fl_chart: ^0.65.0         # Pie charts & bar charts
  intl: ^0.19.0             # For date formatting
  nepali_utils: 3.0.8      # Convert AD <-> BS dates
  provider: ^6.1.2          # Manage app state (optional but recommended)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # --------------------------
  # HIVE MODEL GENERATOR
  # --------------------------
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

